name: "Send Private Message on Zulip"
description: "Triggers a Private Message to the specified Zulip users when code is pushed in the master branch"
author: "MonilBhavsar"
branding:
  icon: message-square
  color: green


runs:
  using: "docker"
  image: "Dockerfile"
